name: findeasy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # audioplayers: ^6.1.0
  fluttertoast: ^8.2.8
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.8.0
  flutter_launcher_icons: ^0.14.2

  geojson_vi: ^2.2.5
  avatar_glow: ^2.0.2 
  latlong2: ^0.9.1
  provider: ^6.1.2
  http: ^1.2.2
  flutter_polyline_points: ^2.1.0

  record: ^5.1.0
  sherpa_onnx: ^1.10.33  

  path_provider: ^2.1.4
  path: ^1.9.0

  # flutter_tts: ^3.6.3 # no sound, strange
  flutter_tts:
    path: ./3rd-party/flutter_tts

  archive: ^4.0.2

  ffi: ^2.1.3

  shared_preferences: ^2.3.4

  dio: ^5.7.0
  geolocator: ^13.0.2
  flutter_compass: ^0.8.1

  permission_handler: ^11.3.1

  pinyin: ^3.3.0
  flutter_riverpod: ^2.6.1
  get_it: ^8.2.0
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: any # Use test for running unit tests
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    # - assets/coast.geojson
    - assets/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/
    - assets/person_top.png
    - assets/icon/app.png
    # - assets/osrm-routed
    # - assets/route.zip

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app.png"
